apiVersion: apps/v1
kind: Deployment
metadata:
  name: fermentation-monitor-scada-mobile
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fermentation-monitor-scada-mobile
  template:
    metadata:
      labels:
        app: fermentation-monitor-scada-mobile
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-16T01:15:00Z"
    spec:
      containers:
      - name: frontend-mobile
        image: ghcr.io/timbenedet/myfermentlab-mobile:scada
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fermentation-monitor-scada-mobile
  namespace: default
spec:
  selector:
    app: fermentation-monitor-scada-mobile
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083
  type: NodePort
