apiVersion: apps/v1
kind: Deployment
metadata:
  name: fermentation-monitor-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fermentation-monitor-test
  template:
    metadata:
      labels:
        app: fermentation-monitor-test
    spec:
      containers:
      - name: frontend
        image: ghcr.io/timbenedet/myfermentlab-frontend:kraft-test
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fermentation-monitor-test
  namespace: default
spec:
  selector:
    app: fermentation-monitor-test
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
