apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myfermentlab-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: myfermentlab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fermentation-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fermentation-backend
            port:
              number: 3001
